# Generated by Django 3.1.14 on 2021-12-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MountainDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain', models.CharField(max_length=200)),
                ('winter_season_open', models.CharField(default='N/A', max_length=50)),
                ('winter_season_close', models.CharField(default='N/A', max_length=50)),
                ('summer_season_open', models.CharField(default='N/A', max_length=50)),
                ('summer_season_close', models.CharField(default='N/A', max_length=50)),
                ('link', models.CharField(default='', max_length=2083)),
            ],
        ),
    ]
